repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        description: Rewrites all Terraform configuration files to a canonical format.
        entry: hooks/terraform_fmt.sh
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
        fail_fast: true

      - id: terraform_docs
        name: Terraform docs
        description: Inserts input and output documentation into README.md (using terraform-docs).
        require_serial: true
        entry: hooks/terraform_docs.sh
        language: script
        files: (\.tf|\.terraform\.lock\.hcl)$
        exclude: \.terraform\/.*$
        fail_fast: true

      - id: terraform_validate
        name: Terraform validate
        description: Validates all Terraform configuration files.
        require_serial: true
        entry: hooks/terraform_validate.sh
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
        fail_fast: true

      - id: terraform_providers_lock
        name: Lock terraform provider versions
        description: Updates provider signatures in dependency lock files.
        require_serial: true
        entry: hooks/terraform_providers_lock.sh
        language: script
        files: (\.terraform\.lock\.hcl)$
        exclude: \.terraform\/.*$
        fail_fast: true

      - id: terraform_tflint
        name: Terraform validate with tflint
        description: Validates all Terraform configuration files with TFLint.
        require_serial: true
        entry: hooks/terraform_tflint.sh
        language: script
        files: (\.tf|\.tfvars)$
        exclude: \.terraform\/.*$
        fail_fast: true

      - id: terraform_tfsec
        name: Terraform validate with tfsec
        description: Static analysis of Terraform templates to spot potential security issues.
        require_serial: true
        entry: hooks/terraform_tfsec.sh
        language: script
        fail_fast: true

      - id: terraform_checkov
        name: Checkov
        description: Runs checkov on Terraform templates.
        entry: hooks/terraform_checkov.sh
        language: script
        always_run: false
        files: \.tf$
        exclude: \.terraform\/.*$
        require_serial: true
        fail_fast: true

      - id: tfupdate
        name: tfupdate
        description: Runs tfupdate on Terraform templates.
        language: script
        entry: hooks/tfupdate.sh
        args:
          - --args=terraform
        files: \.tf$
        require_serial: true
        fail_fast: true

  - repo: local
    hooks:
      - id: terratest
        name: terratest
        entry: tests/complete/precommit.sh
        pass_filenames: false
        types: [ go ]
        language: system
        fail_fast: true
